### ISSUE TITLE
Add support for nose's "stop on first failure" flag

### ISSUE THREAD

**Issue by eloraburns** [eloraburns/ipython_nose#1]
e.g.

``` python
%nose -x
```

will only run tests until the first failure

**Comment by avolkov** [comment]
I figured out how to pull line arguments, but for the life of me find out how to pass Config arguments to nose. Here's a patch with some ugly hacking, maybe it will help -- https://gist.github.com/4069945

**Comment by eloraburns** [comment]
@avolkov Thanks for the effort! I've ended up completely rewriting how the extension works (using a plugin instead of subclassing) and along the way managed to fake nose into thinking that the `%nose magic args here` are actually its `sys.argv` parameters. So things like `-x` "Just Work"!

I had to do some extra hacking around to get `-v` to work, since the plugin eats all of the standard output anyway.
